name: Deploy to LAMP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ciss298.zenren.xyz
          username: deployuser
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.PORT }}
          fingerprint: ${{ secrets.KNOWN_HOSTS }}
          script: |
            cd /var/www/ciss298-TeamProject
            git pull origin main
            echo "DB_HOST=localhost" > .env
            echo "DB_USER=root" >> .env
            echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
            php deploy.php

